# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.7

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/bin/cmake

# The command to remove a file.
RM = /usr/local/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/virtualbloks/github/freenect2_test

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/virtualbloks/github/freenect2_test/bin

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/local/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/virtualbloks/github/freenect2_test/bin/CMakeFiles /home/virtualbloks/github/freenect2_test/bin/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/virtualbloks/github/freenect2_test/bin/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named freenect2_test

# Build rule for target.
freenect2_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 freenect2_test
.PHONY : freenect2_test

# fast build rule for target.
freenect2_test/fast:
	$(MAKE) -f CMakeFiles/freenect2_test.dir/build.make CMakeFiles/freenect2_test.dir/build
.PHONY : freenect2_test/fast

src/Protonect.o: src/Protonect.cpp.o

.PHONY : src/Protonect.o

# target to build an object file
src/Protonect.cpp.o:
	$(MAKE) -f CMakeFiles/freenect2_test.dir/build.make CMakeFiles/freenect2_test.dir/src/Protonect.cpp.o
.PHONY : src/Protonect.cpp.o

src/Protonect.i: src/Protonect.cpp.i

.PHONY : src/Protonect.i

# target to preprocess a source file
src/Protonect.cpp.i:
	$(MAKE) -f CMakeFiles/freenect2_test.dir/build.make CMakeFiles/freenect2_test.dir/src/Protonect.cpp.i
.PHONY : src/Protonect.cpp.i

src/Protonect.s: src/Protonect.cpp.s

.PHONY : src/Protonect.s

# target to generate assembly for a file
src/Protonect.cpp.s:
	$(MAKE) -f CMakeFiles/freenect2_test.dir/build.make CMakeFiles/freenect2_test.dir/src/Protonect.cpp.s
.PHONY : src/Protonect.cpp.s

src/flextGL.o: src/flextGL.cpp.o

.PHONY : src/flextGL.o

# target to build an object file
src/flextGL.cpp.o:
	$(MAKE) -f CMakeFiles/freenect2_test.dir/build.make CMakeFiles/freenect2_test.dir/src/flextGL.cpp.o
.PHONY : src/flextGL.cpp.o

src/flextGL.i: src/flextGL.cpp.i

.PHONY : src/flextGL.i

# target to preprocess a source file
src/flextGL.cpp.i:
	$(MAKE) -f CMakeFiles/freenect2_test.dir/build.make CMakeFiles/freenect2_test.dir/src/flextGL.cpp.i
.PHONY : src/flextGL.cpp.i

src/flextGL.s: src/flextGL.cpp.s

.PHONY : src/flextGL.s

# target to generate assembly for a file
src/flextGL.cpp.s:
	$(MAKE) -f CMakeFiles/freenect2_test.dir/build.make CMakeFiles/freenect2_test.dir/src/flextGL.cpp.s
.PHONY : src/flextGL.cpp.s

src/viewer.o: src/viewer.cpp.o

.PHONY : src/viewer.o

# target to build an object file
src/viewer.cpp.o:
	$(MAKE) -f CMakeFiles/freenect2_test.dir/build.make CMakeFiles/freenect2_test.dir/src/viewer.cpp.o
.PHONY : src/viewer.cpp.o

src/viewer.i: src/viewer.cpp.i

.PHONY : src/viewer.i

# target to preprocess a source file
src/viewer.cpp.i:
	$(MAKE) -f CMakeFiles/freenect2_test.dir/build.make CMakeFiles/freenect2_test.dir/src/viewer.cpp.i
.PHONY : src/viewer.cpp.i

src/viewer.s: src/viewer.cpp.s

.PHONY : src/viewer.s

# target to generate assembly for a file
src/viewer.cpp.s:
	$(MAKE) -f CMakeFiles/freenect2_test.dir/build.make CMakeFiles/freenect2_test.dir/src/viewer.cpp.s
.PHONY : src/viewer.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... freenect2_test"
	@echo "... src/Protonect.o"
	@echo "... src/Protonect.i"
	@echo "... src/Protonect.s"
	@echo "... src/flextGL.o"
	@echo "... src/flextGL.i"
	@echo "... src/flextGL.s"
	@echo "... src/viewer.o"
	@echo "... src/viewer.i"
	@echo "... src/viewer.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

